language: go

go:
- '1.13.x'

git:
  quiet: true

cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

env:
- GO111MODULE=on

branches:
  only:
  - master

install: true

matrix:
  fast_finish: true

script: make test-acc
