steps:
- id: test
  name: golang:1.13
  entrypoint: make
  args: ['test-acc']

- id: build
  name: golang:1.13
  entrypoint: make
  args: ['build']

- id: compress
  name: golang:1.13
  entrypoint: make
  args: ['compress']

- id: publish
  name: buildkite/github-release:latest
  env:
  - GITHUB_RELEASE_REPOSITORY=sethvargo/terraform-provider-filesystem
  - GITHUB_RELEASE_COMMIT=$COMMIT_SHA
  - GITHUB_RELEASE_TAG=$TAG_NAME
  secretEnv:
  - GITHUB_RELEASE_ACCESS_TOKEN
  args:
  - $TAG_NAME
  - build/darwin_amd64.tgz
  - build/linux_amd64.tgz
  - build/windows_amd64.tgz

secrets:
- kmsKeyName: projects/sethvargo-cicd/locations/global/keyRings/terraform-provider-filesystem/cryptoKeys/github-token
  secretEnv:
    GITHUB_RELEASE_ACCESS_TOKEN: CiQAOj3Ti8o1VZapIKICCUaKvR2tgSJU3Ybef3zGvqbDpw9ghTASUQAowVLMfxHtCgKEoVZl1SjL/ICZrnf+lKvD507OZ24H0QcssS84ENvwDIz+Jz0lN3NqLhaZsZC044IHu5fDLCem3bHWHr5lWhlKHS/a5kcURQ==
